sudo: false
language: python
python:
  - "3.7"
install:
  - pip install -r requirements-travis.txt
  - pip install -e .
script: pytest
cache: pip
notifications:
   slack: skydreams:1FLUnEeqaNLinKq1p0lJf9F5
